# Generated by Django 6.0.6 on 2026-06-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nazione', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=250)),
                ('anno', models.IntegerField()),
                ('genere', models.CharField(max_length=60)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.autore')),
            ],
        ),
    ]
